spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/tinder
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug #띄어쓰기 2칸
    org.hibernate.type: trace #띄어쓰기 2칸  / sql 실행 파라미터의 타입을 말해줌
